### ISSUE TITLE
Bill of materials?

### ISSUE THREAD

**Issue by desertkun** [spectrumero/spectranet#7]
I understand that I can export one from `spectranet.pcb` but part number specifics are unclear.

**Comment by spectrumero** [comment]
The BOM that I used is in this zip file (sorry, Excel - it's what the assemblers required) for QuickTeck (PCB assembly house who built 100 boards for me). The BOM is only for the SMD parts - I soldered the connectors, jumpers, Ethernet magjack (note: the jack has to have integrated magnetics and the same pinout as the Tyco Mag-45), and LEDs on that run of boards. Important: the LEDs have built in resistors (e.g. Farnell part 1581221).

[spectranet-assy.zip](https://github.com/spectrumero/spectranet/files/5402715/spectranet-assy.zip)

**Comment by spectrumero** [comment]
Also note that the issue 3 board has a different flash chip (it's physically narrower). The issue 3 board is still work in progress. The change is because the Am29F010 (and equivalent) is getting very hard to find as it's now out of production, and the only 5 volt flash still made is in the narrower TSOP32B style package.
